// Code generated by Kitex v0.6.1. DO NOT EDIT.

package pick

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	api "work6/kitex_demo/kitex_gen/api"
)

func serviceInfo() *kitex.ServiceInfo {
	return pickServiceInfo
}

var pickServiceInfo = NewServiceInfo()

func NewServiceInfo() *kitex.ServiceInfo {
	serviceName := "Pick"
	handlerType := (*api.Pick)(nil)
	methods := map[string]kitex.MethodInfo{
		"pick": kitex.NewMethodInfo(pickHandler, newPickPickArgs, newPickPickResult, false),
	}
	extra := map[string]interface{}{
		"PackageName": "api",
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.6.1",
		Extra:           extra,
	}
	return svcInfo
}

func pickHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*api.PickPickArgs)
	realResult := result.(*api.PickPickResult)
	success, err := handler.(api.Pick).Pick(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newPickPickArgs() interface{} {
	return api.NewPickPickArgs()
}

func newPickPickResult() interface{} {
	return api.NewPickPickResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) Pick(ctx context.Context, req *api.Request) (r *api.Response, err error) {
	var _args api.PickPickArgs
	_args.Req = req
	var _result api.PickPickResult
	if err = p.c.Call(ctx, "pick", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
