// Code generated by goctl. DO NOT EDIT.
package types

type Request struct {
	Name  string `json:"name"`
	Price string `json:"price"`
	Num   int `json:"num"`
}

type Response struct {
	Price string `json:"price"`
	Num   int    `json:"num"`
}
