// Code generated by Kitex v0.6.1. DO NOT EDIT.
package nlp

import (
	server "github.com/cloudwego/kitex/server"
	nlp "work6/gotuber-test-demo/kitex_gen/nlp"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler nlp.Nlp, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}
